# Generated by Django 5.0.1 on 2024-03-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr', models.CharField(default='USD', max_length=50)),
                ('value', models.FloatField(default=0.0)),
                ('Symbol', models.CharField(default='$', max_length=3)),
            ],
        ),
    ]
