# Generated by Django 5.0.1 on 2024-04-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencymodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_table',
            name='curr_S',
            field=models.CharField(default='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='currency_table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
